name: remark-lint Check

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2
    - name: Run remark-lint with reviewdog
      # You may pin to the exact commit or the version.
      # uses: reviewdog/action-remark-lint@67b6b605777eb1f119ba445a53a5af39d4a4568d
      uses: reviewdog/action-remark-lint@v2.0.0
      with:
        # Working directory relative to the root directory.
        workdir: ./docs
        level: warning
        fail_on_error: true
