name: remark-lint PR

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.4
      with:
        node-version: 12.x
    - name: Install dependencies
      run: |
        npm install
        npx remark ./docs -o -S
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        title: ":pencil2: remark-lint fix typo"
